openapi: 3.0.0
servers:
- description: Snowflake Result API
  url: https://org-account.snowflakecomputing.com
info:
  version: 0.0.1
  title: Snowflake Result API
  description: The Snowflake Result API is a REST API that you can use to check request
    status and fetch request response.
  contact:
    name: Snowflake, Inc.
    url: https://snowflake.com
    email: support@snowflake.com
paths:
  /api/v2/results/{result_handler}:
    get:
      summary: Check result status or fetch request
      tags:
      - result
      description: Get result status or the result when it is ready.
      operationId: fetchResult
      parameters:
      - name: result_handler
        in: path
        required: true
        schema:
          type: string
        description: The opaque result id.
      - name: page
        in: query
        required: false
        schema:
          type: integer
          format: int64
          minimum: 0
          default: 0
        description: Number of the page of results to return. The number can range
          from 0 to the total number of pages minus 1.
      responses:
        '200':
          description: successful
          headers:
            X-Snowflake-Request-ID:
              $ref: common.yaml#/components/headers/X-Snowflake-Request-ID
            Link:
              $ref: common.yaml#/components/headers/Link
          content:
            application/json: {}
        '202':
          $ref: common.yaml#/components/responses/202SuccessAcceptedResponse
        '400':
          $ref: common.yaml#/components/responses/400BadRequest
        '401':
          $ref: common.yaml#/components/responses/401Unauthorized
        '403':
          $ref: common.yaml#/components/responses/403Forbidden
        '404':
          $ref: common.yaml#/components/responses/404NotFound
        '405':
          $ref: common.yaml#/components/responses/405MethodNotAllowed
        '408':
          $ref: common.yaml#/components/responses/408RequestTimeout
        '409':
          $ref: common.yaml#/components/responses/409Conflict
        '500':
          $ref: common.yaml#/components/responses/500InternalServerError
        '503':
          $ref: common.yaml#/components/responses/503ServiceUnavailable
        '504':
          $ref: common.yaml#/components/responses/504GatewayTimeout
components:
  securitySchemes:
    KeyPair:
      $ref: common.yaml#/components/securitySchemes/KeyPair
    ExternalOAuth:
      $ref: common.yaml#/components/securitySchemes/ExternalOAuth
    SnowflakeOAuth:
      $ref: common.yaml#/components/securitySchemes/SnowflakeOAuth
security:
- KeyPair: []
- ExternalOAuth: []
- SnowflakeOAuth: []
